# Generated by Django 4.2.16 on 2026-06-12 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concessions', '0001_initial'),
        ('caveaux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('motif', models.CharField(choices=[('TRANSFERT', 'Transfert vers un autre cimetière'), ('RENOVATION', 'Rénovation du caveau'), ('FAMILIAL', 'Regroupement familial'), ('JUDICIAIRE', 'Ordonnance judiciaire'), ('AUTRE', 'Autre motif')], max_length=20)),
                ('motif_detail', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('EFFECTUEE', 'Effectuée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=15)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_exhumation_prevue', models.DateField(blank=True, null=True)),
                ('date_exhumation_reelle', models.DateField(blank=True, null=True)),
                ('autorisation_pdf', models.FileField(blank=True, null=True, upload_to='exhumations/autorisations/')),
                ('pv_pdf', models.FileField(blank=True, null=True, upload_to='exhumations/pv/')),
                ('motif_refus', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agent_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_validees', to=settings.AUTH_USER_MODEL)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhumations', to='caveaux.caveau')),
                ('concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations', to='concessions.concession')),
                ('defunt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhumations', to='reservations.defunt')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhumations_demandees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exhumation',
                'verbose_name_plural': 'Exhumations',
                'ordering': ['-date_demande'],
            },
        ),
    ]
